# The name of the application (no spaces)
app_name: redbeds

# First and last name of the user
user: Shanpin Liu

# The NLP product to run the application against
product: NLP352

# How often the application should be run
frequency: monthly

# A list of terms used to subset the corpus
terms: [red bed, red beds, redbed, redbeds, red-bed, red-beds]

# Stored dictionary of terms, to be set by GDD infrastructure admins
dictionary: ???
